import Head from "next/head";
import clsx from "classnames";

// Styles
import styles from "@/styles/Home.module.css";
//Components
import { SearchInput } from "@/components/input";
import { Tabs } from "@/components/tab";
import { CardTable } from "@/components/table";
import { StickySchoolImage } from "@/components/stickySchool";
import { Navbar } from "@/components/nav";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zircon Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StickySchoolImage />
      <Navbar />
      <div className={styles.container}>
        <div className={styles.contentWrapper}>
          <h3 className={styles.h3}>Compare schools</h3>

          <h4 className={clsx(styles.h4, styles.textCenter, styles.pt_2)}>
            Compare top four schools you’re interested in and pick the right one
            for you. <br /> Use the search field to add schools to compare. You
            can drag to reorder schools after selection.
          </h4>

          <SearchInput nav={false} />
          <Tabs />
        </div>
        <CardTable />
      </div>
    </>
  );
}
